version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-app:latest
    volumes:
      - .:/var/www/html
    networks:
      - swarm
    expose:
      - "9000"

  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - database:/var/lib/mysql
    networks:
      - swarm
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - swarm

networks:
  swarm:
    driver: bridge

volumes:
  database:
    driver: local
