version: '3'
services:
  app:
      build:
          context: .
          dockerfile: Dockerfile
      image: my-app:latest
      ports:
        - '${APP_PORT:-80}:80'
      volumes:
        - '.:/var/www/html'
      networks:
        - swarm
      deploy:
        replicas: 3
        resources:
          limits:
            cpus: "0.5"
            memory: 512M
      depends_on:
        - mysql

  mysql:
      image: 'mysql/mysql-server:8.0'
      ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
      volumes:
        - 'database:/var/lib/mysql'
      networks:
        - swarm
      deploy:
        replicas: 3
        resources:
          limits:
            cpus: "0.5"
            memory: 512M
      healthcheck:
        test:
          - CMD
          - mysqladmin
          - ping
          - '-p${DB_PASSWORD}'
        retries: 3
        timeout: 5s

networks:
  swarm:
    driver: overlay

volumes:
  database:
    driver: local
